version: '3.8'
services:
  sqlserver:
    image: lcaohoanq/aps-sqlserver:1.0
    container_name: sqlserver
    ports:
      - "1435:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app_net

  tomcat:
    image: lcaohoanq/aps-tomcat:1.0
    container_name: tomcat
    ports:
      - "8080:8080"
    networks:
      - app_net

volumes:
  sql_data:

networks:
  app_net: